CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    SALARY DECIMAL(10, 2)
);

INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT, SALARY) VALUES
(1, 'Alice', 'HR', 60000.00),
(2, 'Bob', 'Engineering', 80000.00),
(3, 'Charlie', 'Engineering', 75000.00),
(4, 'David', 'Marketing', 50000.00),
(5, 'Eve', 'HR', 62000.00);


SELECT NAME, DEPARTMENT, SALARY
FROM EMPLOYEES
WHERE SALARY > 60000
GROUP BY DEPARTMENT
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC;

DROP TABLE EMPLOYEES;